import { useEffect, useState } from "react";
import {
  AlertTriangle,
  Clock3,
  ShieldAlert,
  Trash2,
} from "lucide-react";

import "./SecurityPages.css";

function ThreatCenter() {
  const [threats, setThreats] = useState([]);

  function loadThreats() {
    const stored = JSON.parse(
      localStorage.getItem("apiSentinelThreats") || "[]"
    );

    setThreats(stored);
  }

  useEffect(() => {
    loadThreats();

    const handleStorage = () => {
      loadThreats();
    };

    window.addEventListener("storage", handleStorage);

    return () => {
      window.removeEventListener(
        "storage",
        handleStorage
      );
    };
  }, []);

  function clearThreats() {
    localStorage.removeItem("apiSentinelThreats");
    setThreats([]);
  }

  const bolaCount = threats.filter(
    (threat) => threat.type === "BOLA"
  ).length;

  const bflaCount = threats.filter(
    (threat) => threat.type === "BFLA"
  ).length;

  return (
    <div className="security-page">
      <header className="security-page-header">
        <div>
          <div className="security-page-title-row">
            <div className="security-page-icon threat-icon">
              <AlertTriangle size={23} />
            </div>

            <div>
              <h1>Threat Center</h1>
              <p>
                Centralized view of API-Sentinel security
                detections and blocked requests.
              </p>
            </div>
          </div>
        </div>

        <div className="security-page-status">
          <span className="online-dot" />
          Monitoring
        </div>
      </header>

      <section className="security-info-grid">
        <div className="security-info-card">
          <span className="security-info-label">
            TOTAL THREATS
          </span>
          <strong>{threats.length}</strong>
          <p>Recorded security detections</p>
        </div>

        <div className="security-info-card">
          <span className="security-info-label">
            BOLA THREATS
          </span>
          <strong>{bolaCount}</strong>
          <p>Object-level authorization</p>
        </div>

        <div className="security-info-card">
          <span className="security-info-label">
            BFLA THREATS
          </span>
          <strong>{bflaCount}</strong>
          <p>Function-level authorization</p>
        </div>
      </section>

      <section className="security-panel">
        <div className="security-panel-header">
          <div>
            <h2>Security Alerts</h2>
            <p>
              Threats generated by runtime security analysis.
            </p>
          </div>

          {threats.length > 0 && (
            <button
              type="button"
              className="security-danger-button"
              onClick={clearThreats}
            >
              <Trash2 size={15} />
              Clear History
            </button>
          )}
        </div>

        {threats.length === 0 ? (
          <div className="empty-threat-state">
            <div className="empty-threat-icon">
              <ShieldAlert size={28} />
            </div>

            <h3>No threats recorded</h3>

            <p>
              Run a BOLA or BFLA test from the detection pages
              to generate a security alert here.
            </p>
          </div>
        ) : (
          <div className="threat-list">
            {threats.map((threat, index) => (
              <div
                className="threat-list-item"
                key={`${threat.detectedAt}-${index}`}
              >
                <div className="threat-list-icon">
                  <ShieldAlert size={19} />
                </div>

                <div className="threat-list-main">
                  <div className="threat-list-title">
                    <strong>{threat.type}</strong>

                    <span
                      className={`severity-pill ${String(
                        threat.severity || "LOW"
                      ).toLowerCase()}`}
                    >
                      {threat.severity || "LOW"}
                    </span>
                  </div>

                  <p>{threat.reason}</p>

                  <div className="threat-list-meta">
                    <span>
                      Endpoint: {threat.endpoint || "Unknown"}
                    </span>

                    <span>
                      <Clock3 size={13} />
                      {new Date(
                        threat.detectedAt
                      ).toLocaleString()}
                    </span>
                  </div>
                </div>

                <div className="threat-status">
                  {threat.status || "Detected"}
                </div>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

export default ThreatCenter;